#!/usr/bin/env python3
"""

_rule_common.py -- Shared rule scaffolding: evidence view, escalation
=====================================================================
SECURITY: READ-ONLY. No credential handling. The only dependency on another
module is _oss_client.session_id(), used to stamp the escalation package with
the same per-run session id that the API calls carry.

Internal module (prefixed with `_`). Do NOT run directly.

Contents
--------
  * SKILL_NAME                 the single source of the skill identifier
  * _request_attributes        the logged fields a conclusion may rest on
  * rule_escalate              verdict C: hand the evidence to support
  * build_escalation_package   the ticket payload for a verdict C run

SKILL_NAME lives here on purpose. The entry script and this module both need
it, and the escalation package used to resolve a name that was never defined
in this module -- a NameError that aborted every verdict-C run. Defining it
once in the lowest shared layer removes that class of bug and is covered by an
assertion in the rules self-test.
"""

from __future__ import annotations

import re

import _oss_client
from _constants import VERDICT_ESCALATE

SKILL_NAME = "alibabacloud-oss-access-log-trace-diagnosis"


def _request_attributes(row: dict) -> dict:
    """The logged attributes that a policy condition is evaluated against."""
    return {
        "operation": row.get("operation", "-"),
        "object": row.get("object", "-"),
        "client_ip": row.get("client_ip", "-"),
        "vpc_id": row.get("vpc_id", "-"),
        "access_id": row.get("access_id", "-"),
        "requester_id": row.get("requester_id", "-"),
        "sign_type": row.get("sign_type", "-"),
        "user_agent": row.get("user_agent", "-"),
        "host": row.get("host", "-"),
        "referer": row.get("referer", "-"),
    }

def rule_escalate(row: dict, entry: dict, ctx: dict) -> dict:
    """Verdict C: the decisive evidence is not reachable from the customer side."""
    return {
        "verdict": VERDICT_ESCALATE,
        "conclusion": entry.get("meaning") or
                      "This failure cannot be diagnosed from the customer side.",
        "root_cause": (
            (entry.get("note") or "") +
            " The evidence that would settle this is held server-side and is "
            "not exposed through any customer-facing API, so this skill reports "
            "it as unverifiable instead of proposing a likely-looking cause."),
        "recommendations": [
            "Open a support ticket and attach the escalation package below.",
            "Do not retry the request repeatedly or re-issue credentials: for a "
            "platform-level denial that changes nothing.",
        ],
        "evidence": {"request_attributes": _request_attributes(row),
                     "ec": entry.get("ec", ""),
                     "error_code": entry.get("error_code", "")},
    }

def build_escalation_package(row: dict, ctx: dict, verdict: dict) -> dict:
    """Assemble the ticket package for a verdict C (or an unresolved B)."""
    return {
        "skill": SKILL_NAME,
        "session_id": _oss_client.session_id(),
        "bucket": ctx["bucket"],
        "region": ctx["region"],
        "owner_uid": ctx["owner_id"] or "(not resolved)",
        "request_id": row.get("request_id", "-"),
        "logged_time": row.get("time", "-"),
        "operation": row.get("operation", "-"),
        "http_status": row.get("http_status", "-"),
        "error_code": row.get("error_code", "-"),
        "ec": row.get("ec", "-"),
        "object": row.get("object", "-"),
        "client_ip": row.get("client_ip", "-"),
        "host": row.get("host", "-"),
        "sign_type": row.get("sign_type", "-"),
        "what_this_skill_verified": ctx.get("verified", []),
        "what_this_skill_could_not_verify": ctx.get("unverifiable", []),
        "conclusion_so_far": verdict.get("conclusion", ""),
        "note": ("Generated by a read-only diagnosis skill. No configuration "
                 "was changed and no credential material is included."),
    }
